### ISSUE TITLE
Support events

### ISSUE THREAD

**Issue by srtonz** [halildurmus/dartwinrt#161]
Now that dart-windows/win32#370 has been closed I was hoping to get BLE device discovery and communication going.

Unfortunately the `BluetoothFindFirstDevice` function [does not work for BLE devices](https://docs.microsoft.com/en-us/windows/win32/api/bluetoothapis/nf-bluetoothapis-bluetoothfindfirstdevice#remarks), and instead it's recommended to use the [`BluetoothLEAdvertisementWatcher`](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementwatcher?view=winrt-22000) class for finding nearby BLE devices.

I've been able to make some progress toward this (thanks to the Calendar example), but I'm struggling to understand how to add event handlers for `Received`and `Stopped` events. Running the `generate.cmd` script with some debug modifications this is the error it's generating:

```dart
Projecting method: add_Received
Unable to project method: add_Received
Exception: Type information missing for GenericTypeModifier, TYPE: Windows.Foundation.TypedEventHandler`2.
#0      TypeProjection.projectType (file:///C:/Projects/win32/tool/projection/type.dart:246:5)
dart-windows/win32#1      TypeProjection.projection (file:///C:/Projects/win32/tool/projection/type.dart:54:21)
dart-windows/win32#2      TypeProjection.dartType (file:///C:/Projects/win32/tool/projection/type.dart:63:26)
dart-windows/win32#3      ParameterProjection.dartProjection (file:///C:/Projects/win32/tool/projection/parameter.dart:20:37)
dart-windows/win32#4      MethodProjection.methodParams.<anonymous closure> (file:///C:/Projects/win32/tool/projection/method.dart:76:42)
dart-windows/win32#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
dart-windows/win32#6      ListIterable.join (dart:_internal/iterable.dart:165:22)
dart-windows/win32#7      MethodProjection.methodParams (file:///C:/Projects/win32/tool/projection/method.dart:76:62)
dart-windows/win32#8      WinRTMethodProjection.toString (file:///C:/Projects/win32/tool/projection/winrt_method.dart:86:37)
dart-windows/win32#9      InterfaceProjection.toString.<anonymous closure> (file:///C:/Projects/win32/tool/projection/interface.dart:201:42)
dart-windows/win32#10     MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
dart-windows/win32#11     ListIterable.join (dart:_internal/iterable.dart:156:22)
dart-windows/win32#12     InterfaceProjection.toString (file:///C:/Projects/win32/tool/projection/interface.dart:201:54)
dart-windows/win32#13     generateWinRTApis (file:///C:/Projects/win32/tool/generation/generate_winrt_apis.dart:27:43)
dart-windows/win32#14     main (file:///C:/Projects/win32/tool/generation/generate.dart:36:3)
dart-windows/win32#15     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
dart-windows/win32#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
``` 

I'd be happy to give this a go, but unsure where to start and whether this is currently possible at all?

**Comment by azimuthdeveloper** [comment]
@srtonz I did that for a while but I could never get my app to be stable. I ended up writing the entire Windows bit in Rust which has been rock solid. I might do an article or YouTube video on how to do it.
